server:
  port: 8080
spring:
  mvc:
    path match:
      matching-strategy: path_pattern_parser
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///jdyy
    username: root
    password: 123456
  servlet:
    multipart:
      max-file-size: 30MB #最大文件大小
      max-request-size: 40MB #最大请求大小
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
sa-token:
  # token 名称 (同时也是cookie名称)
  token-name: sa-token
  # token 有效期，单位s 默认30天, -1代表永不过期
  timeout: 2592000
  # token 临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  activity-timeout: -1
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: false
  # token风格
  token-style: uuid
  # 是否输出操作日志
  is-log: false

#swagger
springfox:
  documentation:
    swagger-ui:
      enabled: true # swagger 开启文档显示
#swagger美化
knife4j:
  enable: true # 开启增强
  production: false #生产模式
  basic:
    enable: false # 是否登录
    username: admin
    password: 123456